#!/bin/bash
yum update -y
#debugging 
yum install telnet nc net-tools httpd -y
#ssm 
yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
systemctl start amazon-ssm-agent
systemctl status amazon-ssm-agent
#es setup
cd /opt
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.7.0-linux-x86_64.tar.gz
tar -xzf elasticsearch-8.7.0-linux-x86_64.tar.gz
rm -f elasticsearch-8.7.0-linux-x86_64.tar.gz
ln -s /opt/elasticsearch-8.7.0 elasticsearch
chown -R ec2-user:ec2-user elastic* 
su - ec2-user
whoami
nohup /opt/elasticsearch/bin/elasticsearch &


#kibana
#!/bin/bash
yum update -y
#debugging 
yum install telnet nc net-tools httpd -y
#ssm 
yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
systemctl start amazon-ssm-agent
systemctl status amazon-ssm-agent
cd /opt
curl -O https://artifacts.elastic.co/downloads/kibana/kibana-8.7.0-linux-x86_64.tar.gz 
tar -xzf kibana-8.7.0-linux-x86_64.tar.gz
rm -f kibana-8.7.0-linux-x86_64.tar.gz
ln -s kibana-8.7.0 kibana
chown -R ec2-user:ec2-user kibana* 
su - ec2-user
nohup /opt/kibana/bin/kibana & 

#filebeat 
curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.7.0-linux-x86_64.tar.gz
tar xzvf filebeat-8.7.0-linux-x86_64.tar.gz



#!/bin/bash
pid=$(ps -ef | grep filebeat | awk '{print $2}' | head -1)
kill -9 $pid 
sleep 3 
nohup /opt/filebeat/filebeat &
ps -ef | grep -i filebeat
